#!/usr/bin/env python3
"""build_catalog.py — regenerate catalog.json + llms.txt from all sidecars.

Sweeps every `<file>.meta.json` data card under data/ and prr-templates/ and
rebuilds the two repo-root machine indexes so they always reflect 100% of the
sidecars (rather than drifting behind a folder-by-folder rollout):

  * catalog.json — full machine-readable index (one entry per dataset).
  * llms.txt     — human/LLM-friendly index grouped by top-level collection,
                   one line per dataset with a short blurb + confidence tier.

llms.txt blurbs are auto-derived (first sentence of each card's `description`).
Full detail (columns, notes, source, caveats) stays in the sidecars.

Usage:
  python scripts/build_catalog.py            # write the files
  python scripts/build_catalog.py --check    # exit 1 if outputs would change
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE_DIRS = ["data", "prr-templates"]
CATALOG_PATH = REPO / "catalog.json"
LLMS_PATH = REPO / "llms.txt"

# Section ordering + titles for llms.txt. Any collection not listed here is
# appended afterwards in alphabetical order under a generated title.
SECTION_TITLES = {
    "data/ssa": "SSA datasets (data/ssa)",
    "data/contract": "Contract (data/contract)",
    "data/ma-annual-reports": "MassAbility / MRC / SRC annual reports (data/ma-annual-reports)",
    "data/ra-process": "Reasonable-accommodation process (data/ra-process)",
    "data/labor-rights": "Labor rights & enforcement (data/labor-rights)",
    "data/pay-scales": "Pay scales — MA + peer states (data/pay-scales)",
    "data/cthru-staffing": "CTHRU staffing & leadership (data/cthru-staffing)",
    "data/workload": "Workload evidence (data/workload)",
    "data/prr-responses": "Public-records responses (data/prr-responses)",
    "data/oversight": "Oversight — GAO/OIG (data/oversight)",
    "data/external": "External research & peer organizations (data/external)",
    "data/screenshots": "Screenshots (data/screenshots)",
    "prr-templates": "Public-records / FOIA request templates (prr-templates)",
}

LLMS_HEADER = """# 509dds-data

> Open data, source documents, and analysis for SEIU Local 509's Disability
> Determination Services (DDS) chapter in Massachusetts. DDS = Disability
> Determination Services (adjudicates SSI/SSDI claims), NOT the Department of
> Developmental Services. Audience: union stewards, bargaining-team negotiators,
> 509dds.com developers, and researchers.

Every dataset has a `<file>.meta.json` data card (schema: `schemas/dataset.meta.schema.json`).
The full machine index is `catalog.json`. Confidence tiers: Authoritative,
Computed, Browser-fetch pending, PRR-pending, Structurally unavailable.
This file and catalog.json are generated by `scripts/build_catalog.py`.
"""


def collection_of(path: str) -> str:
    """Top-level collection key for grouping, e.g. 'data/ssa' or 'prr-templates'."""
    parts = path.split("/")
    if parts[0] == "data" and len(parts) > 1:
        return f"data/{parts[1]}"
    return parts[0]


def first_sentence(text: str, cap: int = 160) -> str:
    text = " ".join((text or "").split())
    m = re.search(r"(.+?[.!?])(\s|$)", text)
    s = m.group(1) if m else text
    if len(s) > cap:
        s = s[: cap - 1].rstrip() + "…"
    return s


def load_cards():
    cards = []
    for d in SOURCE_DIRS:
        base = REPO / d
        if not base.exists():
            continue
        for meta in base.rglob("*.meta.json"):
            data = json.loads(meta.read_text(encoding="utf-8"))
            cards.append((meta, data))
    return cards


def build_catalog(cards):
    datasets = []
    for meta, d in cards:
        entry = {
            "id": d.get("id"),
            "title": d.get("title"),
            "path": d.get("path"),
            "meta": meta.relative_to(REPO).as_posix(),
            "format": d.get("format"),
            "confidence_tier": d.get("confidence_tier"),
        }
        if isinstance(d.get("temporal_coverage"), dict):
            entry["temporal_coverage"] = d["temporal_coverage"]
        datasets.append(entry)
    datasets.sort(key=lambda e: (e["path"] or ""))
    return {
        "$comment": (
            "Repo-wide machine-readable dataset index for 509dds-data. "
            "Regenerated from ALL <file>.meta.json sidecars by scripts/build_catalog.py. "
            "Validate with scripts/validate_catalog.py."
        ),
        "repo": "Woop91/509dds-data",
        "schema": "schemas/dataset.meta.schema.json",
        "generated_from": "all data/**/*.meta.json + prr-templates/**/*.meta.json (scripts/build_catalog.py)",
        "dataset_count": len(datasets),
        "datasets": datasets,
    }


def render_catalog(catalog) -> str:
    """One compact line per dataset entry (matches the repo's hand-authored style)."""
    head = {k: catalog[k] for k in ("$comment", "repo", "schema", "generated_from", "dataset_count")}
    lines = ["{"]
    for k, v in head.items():
        lines.append(f"  {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)},")
    lines.append('  "datasets": [')
    rows = [f"    {json.dumps(e, ensure_ascii=False)}" for e in catalog["datasets"]]
    lines.append(",\n".join(rows))
    lines.append("  ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_llms(catalog) -> str:
    by_coll: dict[str, list] = {}
    for e in catalog["datasets"]:
        by_coll.setdefault(collection_of(e["path"]), []).append(e)
    ordered = [c for c in SECTION_TITLES if c in by_coll]
    ordered += sorted(c for c in by_coll if c not in SECTION_TITLES)

    out = [LLMS_HEADER, f"\n_{catalog['dataset_count']} datasets indexed._\n"]
    for coll in ordered:
        title = SECTION_TITLES.get(coll, coll)
        out.append(f"\n## {title}\n")
        for e in sorted(by_coll[coll], key=lambda x: x["path"]):
            card = next(d for m, d in CARDS if d.get("path") == e["path"])
            blurb = first_sentence(card.get("description", ""))
            out.append(f"- [{e['title']}]({e['path']}): {blurb} {e['confidence_tier']}.")
    return "\n".join(out) + "\n"


CARDS = []


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if outputs would change (no write)")
    args = ap.parse_args()

    global CARDS
    CARDS = load_cards()
    catalog = build_catalog(CARDS)
    catalog_txt = render_catalog(catalog)
    llms_txt = render_llms(catalog)

    if args.check:
        changed = []
        if not CATALOG_PATH.exists() or CATALOG_PATH.read_text(encoding="utf-8") != catalog_txt:
            changed.append("catalog.json")
        if not LLMS_PATH.exists() or LLMS_PATH.read_text(encoding="utf-8") != llms_txt:
            changed.append("llms.txt")
        if changed:
            print(f"OUT OF DATE: {', '.join(changed)} — run scripts/build_catalog.py")
            sys.exit(1)
        print(f"up to date ({catalog['dataset_count']} datasets)")
        return

    CATALOG_PATH.write_text(catalog_txt, encoding="utf-8")
    LLMS_PATH.write_text(llms_txt, encoding="utf-8")
    print(f"wrote catalog.json + llms.txt ({catalog['dataset_count']} datasets)")


if __name__ == "__main__":
    main()
