#!/usr/bin/env python3
"""build_embeddings.py — build the semantic vector index from data cards.

Sweeps every <file>.meta.json, composes a deterministic embedding document per
card, embeds it offline with BAAI/bge-small-en-v1.5 (ONNX via fastembed), and
writes embeddings/index.bin (packed Float32, L2-normalized) + manifest.json.

Usage:
  python scripts/build_embeddings.py            # write the artifact
  python scripts/build_embeddings.py --check     # exit 1 if it would change
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _cards import REPO, embedding_document, load_cards  # noqa: E402

MODEL = "BAAI/bge-small-en-v1.5"
MODEL_JS = "Xenova/bge-small-en-v1.5"
DIM = 384
QUERY_INSTRUCTION = "Represent this sentence for searching relevant passages: "
OUT_DIR = REPO / "embeddings"

_embedder = None  # lazy fastembed singleton


def _normalize(vecs: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(vecs, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return (vecs / norms).astype(np.float32)


def embed_texts(texts: list[str]) -> np.ndarray:
    """Embed passages with the real model. Lazy-loads fastembed."""
    global _embedder
    if _embedder is None:
        from fastembed import TextEmbedding
        _embedder = TextEmbedding(model_name=MODEL)
    vecs = np.array(list(_embedder.embed(texts)), dtype=np.float32)
    return _normalize(vecs)


def embed_query(query: str) -> np.ndarray:
    """Embed a single search query (with the bge query instruction)."""
    vec = embed_texts([QUERY_INSTRUCTION + query])
    return vec[0]


def build(cards, embedder=embed_texts):
    docs = [embedding_document(c) for _, c in cards]
    vecs = embedder(docs)
    vectors = [
        {"id": c.get("id"), "path": c.get("path"), "title": c.get("title"),
         "tags": c.get("tags") or []}
        for _, c in cards
    ]
    manifest = {
        "$comment": "Semantic index for 509dds-data. Generated by scripts/build_embeddings.py.",
        "model": MODEL,
        "model_js": MODEL_JS,
        "dim": DIM,
        "normalized": True,
        "query_instruction": QUERY_INSTRUCTION,
        "count": len(vectors),
        "vectors": vectors,
    }
    return vecs, manifest


def pack(vecs: np.ndarray) -> bytes:
    return vecs.astype("<f4").tobytes()


def unpack(blob: bytes, dim: int) -> np.ndarray:
    return np.frombuffer(blob, dtype="<f4").reshape(-1, dim).copy()


def write_artifact(vecs: np.ndarray, manifest: dict, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index.bin").write_bytes(pack(vecs))
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def load_artifact(out_dir: Path):
    manifest = json.loads((out_dir / "manifest.json").read_text(encoding="utf-8"))
    vecs = unpack((out_dir / "index.bin").read_bytes(), manifest["dim"])
    return vecs, manifest


def check(cards, out_dir=OUT_DIR, embedder=embed_texts, atol=1e-5):
    """Return list of artifact files that a rebuild would change ([] = up to date)."""
    new_vecs, new_manifest = build(cards, embedder=embedder)
    changed = []
    if not (out_dir / "index.bin").exists() or not (out_dir / "manifest.json").exists():
        return ["index.bin", "manifest.json"]
    old_vecs, old_manifest = load_artifact(out_dir)
    if old_vecs.shape != new_vecs.shape or not np.allclose(old_vecs, new_vecs, atol=atol):
        changed.append("index.bin")
    # manifest holds only metadata (no float vectors — those are in index.bin); compare it whole
    if json.dumps(old_manifest, sort_keys=True) != json.dumps(new_manifest, sort_keys=True):
        changed.append("manifest.json")
    return changed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the artifact would change")
    args = ap.parse_args()
    cards = load_cards()
    if args.check:
        changed = check(cards, OUT_DIR)
        if changed:
            print(f"OUT OF DATE: {', '.join(changed)} — run scripts/build_embeddings.py")
            sys.exit(1)
        print(f"up to date ({len(cards)} cards embedded)")
        return
    vecs, manifest = build(cards)
    write_artifact(vecs, manifest, OUT_DIR)
    print(f"wrote embeddings/index.bin + manifest.json ({manifest['count']} vectors, dim {DIM})")


if __name__ == "__main__":
    main()
