#!/usr/bin/env python3
"""build_embeddings.py — build the semantic vector index from data cards.

Sweeps every <file>.meta.json, composes a deterministic embedding document per
card, embeds it offline with BAAI/bge-small-en-v1.5 (ONNX via fastembed), and
writes embeddings/index.bin (packed Float32, L2-normalized) + manifest.json.

Usage:
  python scripts/build_embeddings.py            # write the artifact
  python scripts/build_embeddings.py --check     # exit 1 if it would change
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _cards import REPO, embedding_document, load_cards  # noqa: E402

MODEL = "BAAI/bge-small-en-v1.5"
MODEL_JS = "Xenova/bge-small-en-v1.5"
DIM = 384
QUERY_INSTRUCTION = "Represent this sentence for searching relevant passages: "
OUT_DIR = REPO / "embeddings"

_embedder = None  # lazy fastembed singleton


def _normalize(vecs: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(vecs, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return (vecs / norms).astype(np.float32)


def embed_texts(texts: list[str]) -> np.ndarray:
    """Embed passages with the real model. Lazy-loads fastembed."""
    global _embedder
    if _embedder is None:
        from fastembed import TextEmbedding
        _embedder = TextEmbedding(model_name=MODEL)
    vecs = np.array(list(_embedder.embed(texts)), dtype=np.float32)
    return _normalize(vecs)


def build(cards, embedder=embed_texts):
    docs = [embedding_document(c) for _, c in cards]
    vecs = embedder(docs)
    vectors = [
        {"id": c.get("id"), "path": c.get("path"), "title": c.get("title"),
         "tags": c.get("tags") or []}
        for _, c in cards
    ]
    manifest = {
        "$comment": "Semantic index for 509dds-data. Generated by scripts/build_embeddings.py.",
        "model": MODEL,
        "model_js": MODEL_JS,
        "dim": DIM,
        "normalized": True,
        "query_instruction": QUERY_INSTRUCTION,
        "count": len(vectors),
        "vectors": vectors,
    }
    return vecs, manifest


def pack(vecs: np.ndarray) -> bytes:
    return vecs.astype("<f4").tobytes()


def unpack(blob: bytes, dim: int) -> np.ndarray:
    return np.frombuffer(blob, dtype="<f4").reshape(-1, dim).copy()
