#!/usr/bin/env python3
"""suggest_related.py — emit a HUMAN-REVIEW report of candidate `related` edges.

Advisory only: writes reports/related-suggestions.json. Does NOT modify cards.

Heuristic: within a collection directory (the data file's immediate parent),
sibling cards are candidate `related` pairs — but ONLY for SMALL clusters
(<= max_cluster members). Large clusters (e.g. the 60-card NADE state-bylaws
folder) would form a useless full clique, so they are FLAGGED for topical
curation instead of pairwise-suggested. Pairs already mutually linked are skipped.
"""
from __future__ import annotations

import argparse
import json
import sys
from itertools import combinations
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _cards import REPO, load_cards  # noqa: E402

REPORT_PATH = REPO / "reports" / "related-suggestions.json"
MAX_CLUSTER = 4


def collection_dir(path: str) -> str:
    return path.rsplit("/", 1)[0]


def propose(cards, max_cluster: int = MAX_CLUSTER) -> dict:
    by_id = {c.get("id"): c for _, c in cards}
    dirs: dict[str, list[str]] = {}
    for _, c in cards:
        dirs.setdefault(collection_dir(c.get("path", "")), []).append(c.get("id"))
    suggestions = []
    skipped = []
    for d, ids in sorted(dirs.items()):
        if len(ids) < 2:
            continue
        if len(ids) > max_cluster:
            skipped.append({"dir": d, "size": len(ids),
                            "reason": "cluster too large for sibling-linking; curate topically"})
            continue
        for a, b in combinations(sorted(ids), 2):
            ca, cb = by_id[a], by_id[b]
            if b in (ca.get("related") or []) and a in (cb.get("related") or []):
                continue  # already mutually linked
            suggestions.append([a, b])
    return {"suggestions": suggestions, "skipped_large_clusters": skipped}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-cluster", type=int, default=MAX_CLUSTER)
    args = ap.parse_args()
    cards = load_cards(REPO)
    res = propose(cards, max_cluster=args.max_cluster)
    res = {"$comment": ("Advisory candidate `related` edges for human review. "
                        "Generated by scripts/suggest_related.py. Small same-dir clusters only; "
                        "large clusters flagged for topical curation. Not auto-applied."),
           **res}
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps(res, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {REPORT_PATH.relative_to(REPO)}: {len(res['suggestions'])} suggested pairs, "
          f"{len(res['skipped_large_clusters'])} large clusters flagged")


if __name__ == "__main__":
    main()
